# Generated by Django 4.1 on 2024-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_videoupload_upload_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empName',
            field=models.CharField(default='no', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
