# Generated by Django 4.1 on 2024-01-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_videoupload_upload_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(default='Mr', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='upload_datetime',
            field=models.DateTimeField(),
        ),
    ]
